name = "PISP"
uuid = "0cf86302-bd88-49fb-82d1-7e27fc78d6eb"
authors = ["Pablo Apablaza <papablaza@student.unimelb.edu.au> and contributors"]
version = "1.0.0-DEV"

[deps]
Arrow = "69666777-d1a9-59fb-9406-91d4454c9d45"
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
Cascadia = "54eefc05-d75b-58de-a785-1a3403f0919f"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
Downloads = "f43a241f-c20a-4ad4-852c-f6b1247861c6"
Gumbo = "708ec375-b3d6-5a57-a7ce-8257bf98657a"
HTTP = "cd3eb016-35fb-5094-929b-558a96fad6f3"
OrderedCollections = "bac558e1-5e72-5ebc-8fee-abe8a469f55d"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
Tables = "bd369af6-aec1-5ad0-b16a-f7cc5008161c"
XLSX = "fdbf4ff8-1666-58a4-91e7-1b58723a45e0"

[compat]
Arrow = "2.8.0"
CSV = "0.10.15"
Cascadia = "1.0.2"
DataFrames = "1.7"
Downloads = "1.6.0"
Gumbo = "0.8.3"
HTTP = "1.10.19"
OrderedCollections = "1.8.1"
Printf = "1.11.0"
Tables = "1.12.1"
XLSX = "0.10.4"
julia = "1.11"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
